"""Tests for the Alpine APK file adapter and repo adapter."""
import gzip
import io
import os
import shutil
import tarfile
import tempfile

from django.conf import settings
from django.test import TestCase

from adapters.file.apk_adapter import ApkFileAdapter, _parse_pkginfo
from adapters.repo.apk_repo import ApkRepoAdapter
from repo.models import Build, Package, Repository


def _make_apk(directory, pkginfo_text, filename="test-1.0.0-r0.apk"):
    """Create a minimal .apk file (gzipped tar with .PKGINFO)."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tar:
        data = pkginfo_text.encode("utf-8")
        info = tarfile.TarInfo(name=".PKGINFO")
        info.size = len(data)
        tar.addfile(info, io.BytesIO(data))

    apk_path = os.path.join(directory, filename)
    with gzip.open(apk_path, "wb") as gz:
        gz.write(buf.getvalue())
    return apk_path


SAMPLE_PKGINFO = """\
# Generated by abuild
pkgname = mypackage
pkgver = 1.2.3-r0
pkgdesc = A test Alpine package
arch = x86_64
url = https://example.com
license = MIT
builddate = 1700000000
depend = libc-utils
depend = busybox
"""


class ApkFileAdapterTests(TestCase):
    """G1: Tests for the APK file metadata parser."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmpdir)

    def test_parse_basic_metadata(self):
        apk_path = _make_apk(self.tmpdir, SAMPLE_PKGINFO)
        adapter = ApkFileAdapter(apk_path)
        self.assertEqual(adapter.get_name(), "mypackage")
        self.assertEqual(adapter.get_version(), "1.2.3-r0")
        self.assertEqual(adapter.get_architecture(), "x86_64")
        self.assertEqual(adapter.get_description(), "A test Alpine package")

    def test_parse_builddate(self):
        apk_path = _make_apk(self.tmpdir, SAMPLE_PKGINFO)
        adapter = ApkFileAdapter(apk_path)
        bd = adapter.get_builddate()
        self.assertIsNotNone(bd)
        self.assertEqual(bd.year, 2023)

    def test_multi_value_depend(self):
        apk_path = _make_apk(self.tmpdir, SAMPLE_PKGINFO)
        fields = _parse_pkginfo(apk_path)
        self.assertIn("busybox", fields["depend"])
        self.assertIn("libc-utils", fields["depend"])

    def test_missing_pkginfo_returns_defaults(self):
        """An APK without .PKGINFO returns safe defaults."""
        buf = io.BytesIO()
        with tarfile.open(fileobj=buf, mode="w") as tar:
            data = b"just some data"
            info = tarfile.TarInfo(name="somefile.txt")
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))
        apk_path = os.path.join(self.tmpdir, "empty.apk")
        with gzip.open(apk_path, "wb") as gz:
            gz.write(buf.getvalue())

        adapter = ApkFileAdapter(apk_path)
        self.assertEqual(adapter.get_name(), "unknown")
        self.assertEqual(adapter.get_version(), "0")
        self.assertEqual(adapter.get_architecture(), "noarch")

    def test_corrupt_file_returns_defaults(self):
        """A non-APK file returns safe defaults."""
        bad_path = os.path.join(self.tmpdir, "bad.apk")
        with open(bad_path, "wb") as f:
            f.write(b"this is not an apk")
        adapter = ApkFileAdapter(bad_path)
        self.assertEqual(adapter.get_name(), "unknown")


class ApkRepoAdapterTests(TestCase):
    """G2: Tests for the APK repository structure generation."""

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.orig_storage = getattr(settings, "STORAGE_PATH", None)
        self.orig_www = getattr(settings, "REPO_WWW_PATH", None)
        self.orig_keyring = getattr(settings, "KEYRING_PATH", None)

        settings.STORAGE_PATH = os.path.join(self.tmpdir, "storage")
        settings.REPO_WWW_PATH = os.path.join(self.tmpdir, "www")
        settings.KEYRING_PATH = os.path.join(self.tmpdir, "keyring")

        for p in [settings.STORAGE_PATH, settings.REPO_WWW_PATH, settings.KEYRING_PATH]:
            os.makedirs(p, exist_ok=True)

        self.repo = Repository.objects.create(repo_uid="apk-test", repo_type="apk")

    def tearDown(self):
        shutil.rmtree(self.tmpdir)
        if self.orig_storage is not None:
            settings.STORAGE_PATH = self.orig_storage
        if self.orig_www is not None:
            settings.REPO_WWW_PATH = self.orig_www
        if self.orig_keyring is not None:
            settings.KEYRING_PATH = self.orig_keyring

    def _create_package(self, name="tool", version="1.0.0-r0", arch="x86_64"):
        uid = f"aa-{name}-{version}"
        pkg = Package.objects.create(
            repo=self.repo,
            package_uid=uid,
            filename=f"{name}-{version}.apk",
            package_name=name,
            version=version,
            architecture=arch,
            upload_date="2024-06-15T12:00:00Z",
            checksum_sha512="a" * 128,
        )
        storage_path = os.path.join(settings.STORAGE_PATH, pkg.relative_path())
        os.makedirs(os.path.dirname(storage_path), exist_ok=True)
        # Write a minimal valid APK file
        buf = io.BytesIO()
        with tarfile.open(fileobj=buf, mode="w") as tar:
            pkginfo = f"pkgname = {name}\npkgver = {version}\narch = {arch}\n".encode()
            info = tarfile.TarInfo(name=".PKGINFO")
            info.size = len(pkginfo)
            tar.addfile(info, io.BytesIO(pkginfo))
        with gzip.open(storage_path, "wb") as gz:
            gz.write(buf.getvalue())
        return pkg

    def test_generates_apkindex(self):
        self._create_package("tool", "1.0.0-r0")
        self._create_package("tool", "2.0.0-r0")

        adapter = ApkRepoAdapter(self.repo)
        adapter.build = Build.objects.create(
            repo=self.repo, build_number=1, completion_status=Build.STATUS_RUNNING
        )
        adapter.packages = Package.objects.filter(repo=self.repo)

        repo_path = os.path.join(self.tmpdir, "output")
        os.makedirs(repo_path)
        result = adapter._generate_repo_structure(repo_path)

        self.assertTrue(result)

        # Verify APKINDEX.tar.gz exists
        index_path = os.path.join(repo_path, "APKINDEX.tar.gz")
        self.assertTrue(os.path.isfile(index_path))

        # Verify APKINDEX.tar.gz is a valid gzipped tar with APKINDEX inside
        with gzip.open(index_path, "rb") as gz:
            raw = gz.read()
        with tarfile.open(fileobj=io.BytesIO(raw)) as tar:
            names = tar.getnames()
            self.assertIn("APKINDEX", names)
            self.assertIn("DESCRIPTION", names)

            apkindex = tar.extractfile("APKINDEX").read().decode("utf-8")
            self.assertIn("P:tool", apkindex)
            self.assertIn("V:1.0.0-r0", apkindex)
            self.assertIn("V:2.0.0-r0", apkindex)
            self.assertIn("A:x86_64", apkindex)

    def test_empty_repo(self):
        adapter = ApkRepoAdapter(self.repo)
        adapter.build = Build.objects.create(
            repo=self.repo, build_number=1, completion_status=Build.STATUS_RUNNING
        )

        repo_path = os.path.join(self.tmpdir, "output")
        os.makedirs(repo_path)
        result = adapter._generate_repo_structure(repo_path)

        self.assertTrue(result)
        self.assertTrue(os.path.isfile(os.path.join(repo_path, "APKINDEX.tar.gz")))

    def test_get_repo_instructions(self):
        adapter = ApkRepoAdapter(self.repo)
        instructions = adapter._get_repo_instructions()
        self.assertIn("apk-test", instructions)
        self.assertIn("/etc/apk/repositories", instructions)
