blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://opentreecz.github.io/openrepo
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/opentreecz/openrepo/discussions
    about: Ask questions and discuss ideas
