# Generated by Django 6.1 on 2026-09-04 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0013_uploadtask_error_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="architecture",
            field=models.CharField(
                db_index=True,
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Architecture may only contain alphanumeric characters, dots, underscores, hyphens, and plus signs.",
                        regex="^[a-zA-Z0-9_.+-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="promote_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoted_from",
                to="repo.repository",
            ),
        ),
        migrations.AlterField(
            model_name="uploadtask",
            name="error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
